// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_time_screen_init();
    ui_steps_screen_init();
    ui_audio_screen_init();
    ui_images_screen_init();
    ui_settings_screen_init();
    ui_player_screen_init();
    ui_viewerfiles_screen_init();
    ui_files_screen_init();
    ui_viewerimages_screen_init();
    ui_keyboard_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_time);
}

void ui_destroy(void)
{
    ui_time_screen_destroy();
    ui_steps_screen_destroy();
    ui_audio_screen_destroy();
    ui_images_screen_destroy();
    ui_settings_screen_destroy();
    ui_player_screen_destroy();
    ui_viewerfiles_screen_destroy();
    ui_files_screen_destroy();
    ui_viewerimages_screen_destroy();
    ui_keyboard_screen_destroy();
}
