// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_time.h"
#include "ui_steps.h"
#include "ui_audio.h"
#include "ui_images.h"
#include "ui_settings.h"
#include "ui_player.h"
#include "ui_viewerfiles.h"
#include "ui_files.h"
#include "ui_viewerimages.h"
#include "ui_keyboard.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_wifi_strong_green_3arc_25x25_png);    // assets/wifi_strong_green_3arc_25x25.png
LV_IMG_DECLARE(ui_img_battery_strong_green_3bars_25x25_png);    // assets/battery_strong_green_3bars_25x25.png
LV_IMG_DECLARE(ui_img_bg_watch_audio_png);    // assets/BG_Watch_Audio.png
LV_IMG_DECLARE(ui_img_button_play_75_png);    // assets/button_play_75.png
LV_IMG_DECLARE(ui_img_button_pause_75_png);    // assets/button_pause_75.png
LV_IMG_DECLARE(ui_img_button_prev_75_png);    // assets/button_prev_75.png
LV_IMG_DECLARE(ui_img_button_repeat_75_png);    // assets/button_repeat_75.png
LV_IMG_DECLARE(ui_img_button_next_75_png);    // assets/button_next_75.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
