// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_audio;
lv_obj_t * uic_audiolist;
lv_obj_t * ui_audio = NULL;
lv_obj_t * ui_audiolist = NULL;
lv_obj_t * ui_audiotitle = NULL;
// event funtions
void ui_event_audio(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_steps, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_steps_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_images, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_images_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_player, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_player_screen_init);
    }
}

// build funtions

void ui_audio_screen_init(void)
{
    ui_audio = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_audio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_audio, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_audio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Title label
    ui_audiotitle = lv_label_create(ui_audio);
    lv_obj_set_width(ui_audiotitle, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_audiotitle, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_audiotitle, 0);
    lv_obj_set_y(ui_audiotitle, -200);
    lv_obj_set_align(ui_audiotitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_audiotitle, "AUDIO");
    lv_obj_set_style_text_color(ui_audiotitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_audiotitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_audiotitle, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Audio list
    ui_audiolist = lv_list_create(ui_audio);
    lv_obj_set_width(ui_audiolist, 360);
    lv_obj_set_height(ui_audiolist, 350);
    lv_obj_set_x(ui_audiolist, 0);
    lv_obj_set_y(ui_audiolist, 30);
    lv_obj_set_align(ui_audiolist, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_audiolist, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_audiolist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_audiolist, lv_color_hex(0x036D04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_audiolist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_audiolist, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_audio, ui_event_audio, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_audio, ui_event_audio_loaded, LV_EVENT_SCREEN_LOADED, NULL);
    uic_audio = ui_audio;
    uic_audiolist = ui_audiolist;

}

void ui_audio_screen_destroy(void)
{
    if(ui_audio) lv_obj_del(ui_audio);

    // NULL screen variables
    uic_audio = NULL;
    uic_audiolist = NULL;
    ui_audio = NULL;
    ui_audiolist = NULL;
    ui_audiotitle = NULL;

}
