// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_AUDIO_H
#define UI_AUDIO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_audio
extern void ui_audio_screen_init(void);
extern void ui_audio_screen_destroy(void);
extern void ui_event_audio(lv_event_t * e);
extern lv_obj_t * ui_audio;
extern lv_obj_t * ui_audiolist;
extern lv_obj_t * ui_audiotitle;
// CUSTOM VARIABLES
extern lv_obj_t * uic_audio;
extern lv_obj_t * uic_audiolist;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

