// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT TekstSTART

lv_obj_t * ui_tekststart_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_tekststart;
    cui_tekststart = lv_button_create(comp_parent);
    lv_obj_set_width(cui_tekststart, 100);
    lv_obj_set_height(cui_tekststart, 50);
    lv_obj_set_x(cui_tekststart, 0);
    lv_obj_set_y(cui_tekststart, 21);
    lv_obj_set_align(cui_tekststart, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_tekststart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_tekststart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_tekststart, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_tekststart, lv_color_hex(0x06B64B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_tekststart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(cui_tekststart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_tekststart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(cui_tekststart, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_tekststart, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_TEKSTSTART_NUM);
    children[UI_COMP_TEKSTSTART_TEKSTSTART] = cui_tekststart;
    lv_obj_add_event_cb(cui_tekststart, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_tekststart, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_tekststart_create_hook(cui_tekststart);
    return cui_tekststart;
}

