// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project
//
// AANGEPAST: Event handler declaraties voor alle schermen

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

// ===== STAPPEN SCHERM =====
void ui_event_start_clicked(lv_event_t * e);
void ui_event_stop_clicked(lv_event_t * e);
void ui_event_wis_clicked(lv_event_t * e);
void ui_event_save_clicked(lv_event_t * e);

// ===== AUDIO SCHERM =====
void ui_event_audio_loaded(lv_event_t * e);

// ===== IMAGES SCHERM =====
void ui_event_images_loaded(lv_event_t * e);

// ===== FILES SCHERM =====
void ui_event_files_loaded(lv_event_t * e);

// ===== SETTINGS SCHERM =====
void ui_event_settings_loaded(lv_event_t * e);
void ui_event_brightness_changed(lv_event_t * e);
void ui_event_ssid_clicked(lv_event_t * e);
void ui_event_password_clicked(lv_event_t * e);
void ui_event_wifi_toggled(lv_event_t * e);
void ui_event_settings_save_clicked(lv_event_t * e);

// ===== PLAYER SCHERM =====
void ui_event_player_loaded(lv_event_t * e);
void ui_event_play_clicked(lv_event_t * e);
void ui_event_pause_clicked(lv_event_t * e);
void ui_event_prev_clicked(lv_event_t * e);
void ui_event_next_clicked(lv_event_t * e);
void ui_event_repeat_clicked(lv_event_t * e);
void ui_event_volume_changed(lv_event_t * e);

// ===== KEYBOARD SCHERM =====
void ui_event_keyboard_ready(lv_event_t * e);
void ui_event_keyboard_value_changed(lv_event_t * e);
void ui_event_keyboard_gesture(lv_event_t * e);

// ===== VIEWER SCHERMEN =====
void ui_event_viewerimages_loaded(lv_event_t * e);
void ui_event_viewerfiles_loaded(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
