// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_files;
lv_obj_t * uic_fileslist;
lv_obj_t * ui_files = NULL;
lv_obj_t * ui_fileslist = NULL;
lv_obj_t * ui_filestitle = NULL;
// event funtions
void ui_event_files(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_images, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_images_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_settings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_settings_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_viewerfiles, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_viewerfiles_screen_init);
    }
}

// build funtions

void ui_files_screen_init(void)
{
    ui_files = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_files, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_files, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_files, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Title label
    ui_filestitle = lv_label_create(ui_files);
    lv_obj_set_width(ui_filestitle, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_filestitle, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_filestitle, 0);
    lv_obj_set_y(ui_filestitle, -200);
    lv_obj_set_align(ui_filestitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_filestitle, "TEKST BESTANDEN");
    lv_obj_set_style_text_color(ui_filestitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_filestitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_filestitle, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Files list
    ui_fileslist = lv_list_create(ui_files);
    lv_obj_set_width(ui_fileslist, 360);
    lv_obj_set_height(ui_fileslist, 350);
    lv_obj_set_x(ui_fileslist, 0);
    lv_obj_set_y(ui_fileslist, 30);
    lv_obj_set_align(ui_fileslist, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_fileslist, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fileslist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_fileslist, lv_color_hex(0x036D04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_fileslist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_fileslist, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_files, ui_event_files, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_files, ui_event_files_loaded, LV_EVENT_SCREEN_LOADED, NULL);
    uic_files = ui_files;
    uic_fileslist = ui_fileslist;

}

void ui_files_screen_destroy(void)
{
    if(ui_files) lv_obj_del(ui_files);

    // NULL screen variables
    uic_files = NULL;
    uic_fileslist = NULL;
    ui_files = NULL;
    ui_fileslist = NULL;
    ui_filestitle = NULL;

}
