// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_FILES_H
#define UI_FILES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_files
extern void ui_files_screen_init(void);
extern void ui_files_screen_destroy(void);
extern void ui_event_files(lv_event_t * e);
extern lv_obj_t * ui_files;
extern lv_obj_t * ui_fileslist;
extern lv_obj_t * ui_filestitle;
// CUSTOM VARIABLES
extern lv_obj_t * uic_files;
extern lv_obj_t * uic_fileslist;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

