// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_images;
lv_obj_t * uic_imageslist;
lv_obj_t * ui_images = NULL;
lv_obj_t * ui_imageslist = NULL;
lv_obj_t * ui_imagestitle = NULL;
// event funtions
void ui_event_images(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_files, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_files_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_audio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_audio_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_viewerimages, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_viewerimages_screen_init);
    }
}

// build funtions

void ui_images_screen_init(void)
{
    ui_images = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_images, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_images, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_images, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Title label
    ui_imagestitle = lv_label_create(ui_images);
    lv_obj_set_width(ui_imagestitle, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_imagestitle, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_imagestitle, 0);
    lv_obj_set_y(ui_imagestitle, -200);
    lv_obj_set_align(ui_imagestitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_imagestitle, "AFBEELDINGEN");
    lv_obj_set_style_text_color(ui_imagestitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_imagestitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_imagestitle, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Images list
    ui_imageslist = lv_list_create(ui_images);
    lv_obj_set_width(ui_imageslist, 360);
    lv_obj_set_height(ui_imageslist, 350);
    lv_obj_set_x(ui_imageslist, 0);
    lv_obj_set_y(ui_imageslist, 30);
    lv_obj_set_align(ui_imageslist, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_imageslist, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_imageslist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_imageslist, lv_color_hex(0x036D04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_imageslist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_imageslist, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_images, ui_event_images, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_images, ui_event_images_loaded, LV_EVENT_SCREEN_LOADED, NULL);
    uic_images = ui_images;
    uic_imageslist = ui_imageslist;

}

void ui_images_screen_destroy(void)
{
    if(ui_images) lv_obj_del(ui_images);

    // NULL screen variables
    uic_images = NULL;
    uic_imageslist = NULL;
    ui_images = NULL;
    ui_imageslist = NULL;
    ui_imagestitle = NULL;

}
