// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_IMAGES_H
#define UI_IMAGES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_images
extern void ui_images_screen_init(void);
extern void ui_images_screen_destroy(void);
extern void ui_event_images(lv_event_t * e);
extern lv_obj_t * ui_images;
extern lv_obj_t * ui_imageslist;
extern lv_obj_t * ui_imagestitle;
// CUSTOM VARIABLES
extern lv_obj_t * uic_images;
extern lv_obj_t * uic_imageslist;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

