// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_lblkbinput;
lv_obj_t * uic_Keyboard2;
lv_obj_t * uic_keyboard;
lv_obj_t * uic_kbtextarea;
lv_obj_t * ui_keyboard = NULL;
lv_obj_t * ui_keyboard2 = NULL;
lv_obj_t * ui_lblkbinput = NULL;
lv_obj_t * ui_kbtextarea = NULL;
// event funtions

// build funtions

void ui_keyboard_screen_init(void)
{
    ui_keyboard = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_keyboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_keyboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_keyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Textarea for keyboard input
    ui_kbtextarea = lv_textarea_create(ui_keyboard);
    lv_obj_set_width(ui_kbtextarea, 350);
    lv_obj_set_height(ui_kbtextarea, 50);
    lv_obj_set_x(ui_kbtextarea, 0);
    lv_obj_set_y(ui_kbtextarea, -120);
    lv_obj_set_align(ui_kbtextarea, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_kbtextarea, true);
    lv_textarea_set_placeholder_text(ui_kbtextarea, "Typ hier...");
    lv_obj_set_style_text_font(ui_kbtextarea, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_kbtextarea, lv_color_hex(0x036D04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_kbtextarea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_kbtextarea, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_keyboard2 = lv_keyboard_create(ui_keyboard);
    lv_obj_set_width(ui_keyboard2, 400);
    lv_obj_set_height(ui_keyboard2, 200);
    lv_obj_set_x(ui_keyboard2, 0);
    lv_obj_set_y(ui_keyboard2, 100);
    lv_obj_set_align(ui_keyboard2, LV_ALIGN_CENTER);
    lv_keyboard_set_textarea(ui_keyboard2, ui_kbtextarea);

    // Keep label for backward compatibility but hide it
    ui_lblkbinput = lv_label_create(ui_keyboard);
    lv_obj_set_width(ui_lblkbinput, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_lblkbinput, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_lblkbinput, 0);
    lv_obj_set_y(ui_lblkbinput, -180);
    lv_obj_set_align(ui_lblkbinput, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblkbinput, "");
    lv_obj_set_style_text_font(ui_lblkbinput, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblkbinput, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Keyboard ready event callback
    lv_obj_add_event_cb(ui_keyboard2, ui_event_keyboard_ready, LV_EVENT_READY, NULL);

    // Textarea value changed event callback (voor eerste toetsaanslag wissen)
    lv_obj_add_event_cb(ui_kbtextarea, ui_event_keyboard_value_changed, LV_EVENT_VALUE_CHANGED, NULL);

    // Gesture callback voor verticale swipe = terug zonder opslaan
    lv_obj_add_event_cb(ui_keyboard, ui_event_keyboard_gesture, LV_EVENT_GESTURE, NULL);

    uic_keyboard = ui_keyboard;
    uic_Keyboard2 = ui_keyboard2;
    uic_lblkbinput = ui_lblkbinput;
    uic_kbtextarea = ui_kbtextarea;

}

void ui_keyboard_screen_destroy(void)
{
    if(ui_keyboard) lv_obj_del(ui_keyboard);

    // NULL screen variables
    uic_keyboard = NULL;
    ui_keyboard = NULL;
    uic_Keyboard2 = NULL;
    ui_keyboard2 = NULL;
    uic_lblkbinput = NULL;
    ui_lblkbinput = NULL;
    uic_kbtextarea = NULL;
    ui_kbtextarea = NULL;

}
