// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_KEYBOARD_H
#define UI_KEYBOARD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_keyboard
extern void ui_keyboard_screen_init(void);
extern void ui_keyboard_screen_destroy(void);
extern lv_obj_t * ui_keyboard;
extern lv_obj_t * ui_keyboard2;
extern lv_obj_t * ui_lblkbinput;
extern lv_obj_t * ui_kbtextarea;
// CUSTOM VARIABLES
extern lv_obj_t * uic_keyboard;
extern lv_obj_t * uic_Keyboard2;
extern lv_obj_t * uic_lblkbinput;
extern lv_obj_t * uic_kbtextarea;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

