// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_playedsong;
lv_obj_t * uic_volume;
lv_obj_t * uic_next;
lv_obj_t * uic_repeat;
lv_obj_t * uic_prev;
lv_obj_t * uic_pause;
lv_obj_t * uic_play;
lv_obj_t * uic_player;
lv_obj_t * ui_player = NULL;
lv_obj_t * ui_play = NULL;
lv_obj_t * ui_pause = NULL;
lv_obj_t * ui_prev = NULL;
lv_obj_t * ui_repeat = NULL;
lv_obj_t * ui_next = NULL;
lv_obj_t * ui_volume = NULL;
lv_obj_t * ui_playedsong = NULL;
// event funtions
void ui_event_player(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_audio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_audio_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_audio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_audio_screen_init);
    }
}

// build funtions

void ui_player_screen_init(void)
{
    ui_player = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_player, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_player, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_player, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_player, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_player, &ui_img_bg_watch_audio_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_play = lv_image_create(ui_player);
    lv_image_set_src(ui_play, &ui_img_button_play_75_png);
    lv_obj_set_width(ui_play, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_play, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_play, 50);
    lv_obj_set_y(ui_play, 150);
    lv_obj_set_align(ui_play, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_play, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_play, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pause = lv_image_create(ui_player);
    lv_image_set_src(ui_pause, &ui_img_button_pause_75_png);
    lv_obj_set_width(ui_pause, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_pause, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_pause, -50);
    lv_obj_set_y(ui_pause, 150);
    lv_obj_set_align(ui_pause, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pause, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_pause, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_prev = lv_image_create(ui_player);
    lv_image_set_src(ui_prev, &ui_img_button_prev_75_png);
    lv_obj_set_width(ui_prev, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_prev, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_prev, -150);
    lv_obj_set_y(ui_prev, 150);
    lv_obj_set_align(ui_prev, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_prev, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_prev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_repeat = lv_image_create(ui_player);
    lv_image_set_src(ui_repeat, &ui_img_button_repeat_75_png);
    lv_obj_set_width(ui_repeat, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_repeat, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_repeat, 0);
    lv_obj_set_y(ui_repeat, 70);
    lv_obj_set_align(ui_repeat, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_repeat, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_repeat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_next = lv_image_create(ui_player);
    lv_image_set_src(ui_next, &ui_img_button_next_75_png);
    lv_obj_set_width(ui_next, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_next, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_next, 150);
    lv_obj_set_y(ui_next, 150);
    lv_obj_set_align(ui_next, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_next, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_next, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_volume = lv_slider_create(ui_player);
    lv_slider_set_value(ui_volume, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_volume) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_volume, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_volume, 250);  // Verkort van 300 naar 250
    lv_obj_set_height(ui_volume, 15);
    lv_obj_set_x(ui_volume, 0);
    lv_obj_set_y(ui_volume, 225);
    lv_obj_set_align(ui_volume, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_volume, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_volume,
                                                                                             lv_obj_get_style_pad_right(ui_volume, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_playedsong = lv_label_create(ui_player);
    lv_obj_set_width(ui_playedsong, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_playedsong, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_playedsong, 0);
    lv_obj_set_y(ui_playedsong, -200);
    lv_obj_set_align(ui_playedsong, LV_ALIGN_CENTER);
    lv_label_set_text(ui_playedsong, "PLAYED SONG");
    lv_obj_set_style_text_color(ui_playedsong, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_playedsong, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_playedsong, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_playedsong, lv_color_hex(0x036D04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_playedsong, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_playedsong, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_playedsong, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Player button event callbacks
    lv_obj_add_event_cb(ui_play, ui_event_play_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_pause, ui_event_pause_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_prev, ui_event_prev_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_next, ui_event_next_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_repeat, ui_event_repeat_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_volume, ui_event_volume_changed, LV_EVENT_VALUE_CHANGED, NULL);

    // Player screen loaded event
    lv_obj_add_event_cb(ui_player, ui_event_player_loaded, LV_EVENT_SCREEN_LOADED, NULL);
    lv_obj_add_event_cb(ui_player, ui_event_player, LV_EVENT_ALL, NULL);
    uic_player = ui_player;
    uic_play = ui_play;
    uic_pause = ui_pause;
    uic_prev = ui_prev;
    uic_repeat = ui_repeat;
    uic_next = ui_next;
    uic_volume = ui_volume;
    uic_playedsong = ui_playedsong;

}

void ui_player_screen_destroy(void)
{
    if(ui_player) lv_obj_del(ui_player);

    // NULL screen variables
    uic_player = NULL;
    ui_player = NULL;
    uic_play = NULL;
    ui_play = NULL;
    uic_pause = NULL;
    ui_pause = NULL;
    uic_prev = NULL;
    ui_prev = NULL;
    uic_repeat = NULL;
    ui_repeat = NULL;
    uic_next = NULL;
    ui_next = NULL;
    uic_volume = NULL;
    ui_volume = NULL;
    uic_playedsong = NULL;
    ui_playedsong = NULL;

}
