// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_PLAYER_H
#define UI_PLAYER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_player
extern void ui_player_screen_init(void);
extern void ui_player_screen_destroy(void);
extern void ui_event_player(lv_event_t * e);
extern lv_obj_t * ui_player;
extern lv_obj_t * ui_play;
extern lv_obj_t * ui_pause;
extern lv_obj_t * ui_prev;
extern lv_obj_t * ui_repeat;
extern lv_obj_t * ui_next;
extern lv_obj_t * ui_volume;
extern lv_obj_t * ui_playedsong;
// CUSTOM VARIABLES
extern lv_obj_t * uic_player;
extern lv_obj_t * uic_play;
extern lv_obj_t * uic_pause;
extern lv_obj_t * uic_prev;
extern lv_obj_t * uic_repeat;
extern lv_obj_t * uic_next;
extern lv_obj_t * uic_volume;
extern lv_obj_t * uic_playedsong;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

