// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_save;
lv_obj_t * uic_swwifi;
lv_obj_t * uic_password;
lv_obj_t * uic_ssid;
lv_obj_t * uic_percentage;
lv_obj_t * uic_Slider1;
lv_obj_t * uic_helderheid;
lv_obj_t * uic_settings;
lv_obj_t * ui_settings = NULL;
lv_obj_t * ui_helderheid = NULL;
lv_obj_t * ui_slider1 = NULL;
lv_obj_t * ui_percentage = NULL;
lv_obj_t * ui_ssid = NULL;
lv_obj_t * ui_password = NULL;
lv_obj_t * ui_swwifi = NULL;
lv_obj_t * ui_save = NULL;
lv_obj_t * ui_label11 = NULL;
lv_obj_t * ui_label13 = NULL;
lv_obj_t * ui_label14 = NULL;
// event funtions
void ui_event_settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_files, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_files_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_time, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_time_screen_init);
    }
}

void ui_event_slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_percentage, target, "", "");
    }
}

// build funtions

void ui_settings_screen_init(void)
{
    ui_settings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_settings, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_helderheid = lv_label_create(ui_settings);
    lv_obj_set_width(ui_helderheid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_helderheid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_helderheid, -110);
    lv_obj_set_y(ui_helderheid, -175);
    lv_obj_set_align(ui_helderheid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_helderheid, "Helderheid");
    lv_obj_set_style_text_color(ui_helderheid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_helderheid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_helderheid, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slider1 = lv_slider_create(ui_settings);
    lv_slider_set_value(ui_slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_slider1, 350);
    lv_obj_set_height(ui_slider1, 20);
    lv_obj_set_x(ui_slider1, 0);
    lv_obj_set_y(ui_slider1, -136);
    lv_obj_set_align(ui_slider1, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_slider1,
                                                                                              lv_obj_get_style_pad_right(ui_slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_percentage = lv_label_create(ui_settings);
    lv_obj_set_width(ui_percentage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_percentage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_percentage, 50);
    lv_obj_set_y(ui_percentage, -175);
    lv_obj_set_align(ui_percentage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_percentage, "percentage");
    lv_obj_set_style_text_color(ui_percentage, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_percentage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_percentage, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ssid = lv_label_create(ui_settings);
    lv_obj_set_width(ui_ssid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ssid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ssid, 0);
    lv_obj_set_y(ui_ssid, -75);
    lv_obj_set_align(ui_ssid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ssid, "Vul hier uw SSID in");
    lv_obj_add_flag(ui_ssid, LV_OBJ_FLAG_CLICKABLE);     /// Make clickable
    lv_obj_set_style_text_color(ui_ssid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ssid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ssid, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ssid, lv_color_hex(0x036D04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ssid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ssid, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_ssid, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_password = lv_label_create(ui_settings);
    lv_obj_set_width(ui_password, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_password, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_password, LV_ALIGN_CENTER);
    lv_label_set_text(ui_password, "Vul hier uw Wifi wachtwoord in");
    lv_obj_add_flag(ui_password, LV_OBJ_FLAG_CLICKABLE);     /// Make clickable
    lv_obj_set_style_text_color(ui_password, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_password, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_password, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_password, lv_color_hex(0x036D04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_password, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_password, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_password, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swwifi = lv_switch_create(ui_settings);
    lv_obj_set_width(ui_swwifi, 100);
    lv_obj_set_height(ui_swwifi, 50);
    lv_obj_set_x(ui_swwifi, 0);
    lv_obj_set_y(ui_swwifi, 90);
    lv_obj_set_align(ui_swwifi, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_swwifi, lv_color_hex(0xFF0016), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swwifi, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_swwifi, lv_color_hex(0x056D2A), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_swwifi, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_swwifi, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swwifi, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_save = lv_button_create(ui_settings);
    lv_obj_set_width(ui_save, 100);
    lv_obj_set_height(ui_save, 50);
    lv_obj_set_x(ui_save, 0);
    lv_obj_set_y(ui_save, 184);
    lv_obj_set_align(ui_save, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_save, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_save, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_save, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_save, lv_color_hex(0xF905E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_save, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_save, lv_color_hex(0xFBFC09), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_save, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_save, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label11 = lv_label_create(ui_settings);
    lv_obj_set_width(ui_label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label11, 0);
    lv_obj_set_y(ui_label11, 185);
    lv_obj_set_align(ui_label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label11, "Save");
    lv_obj_set_style_text_color(ui_label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label11, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label13 = lv_label_create(ui_settings);
    lv_obj_set_width(ui_label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label13, -90);
    lv_obj_set_y(ui_label13, 90);
    lv_obj_set_align(ui_label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label13, "Uit");
    lv_obj_set_style_text_font(ui_label13, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label14 = lv_label_create(ui_settings);
    lv_obj_set_width(ui_label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label14, 90);
    lv_obj_set_y(ui_label14, 90);
    lv_obj_set_align(ui_label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label14, "Aan");
    lv_obj_set_style_text_font(ui_label14, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_slider1, ui_event_slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_slider1, ui_event_brightness_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_ssid, ui_event_ssid_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_password, ui_event_password_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_swwifi, ui_event_wifi_toggled, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_save, ui_event_settings_save_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_settings, ui_event_settings_loaded, LV_EVENT_SCREEN_LOADED, NULL);
    lv_obj_add_event_cb(ui_settings, ui_event_settings, LV_EVENT_ALL, NULL);
    uic_settings = ui_settings;
    uic_helderheid = ui_helderheid;
    uic_Slider1 = ui_slider1;
    uic_percentage = ui_percentage;
    uic_ssid = ui_ssid;
    uic_password = ui_password;
    uic_swwifi = ui_swwifi;
    uic_save = ui_save;

}

void ui_settings_screen_destroy(void)
{
    if(ui_settings) lv_obj_del(ui_settings);

    // NULL screen variables
    uic_settings = NULL;
    ui_settings = NULL;
    uic_helderheid = NULL;
    ui_helderheid = NULL;
    uic_Slider1 = NULL;
    ui_slider1 = NULL;
    uic_percentage = NULL;
    ui_percentage = NULL;
    uic_ssid = NULL;
    ui_ssid = NULL;
    uic_password = NULL;
    ui_password = NULL;
    uic_swwifi = NULL;
    ui_swwifi = NULL;
    uic_save = NULL;
    ui_save = NULL;
    ui_label11 = NULL;
    ui_label13 = NULL;
    ui_label14 = NULL;

}
