// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_wis;
lv_obj_t * uic_stop;
lv_obj_t * uic_stepscount;
lv_obj_t * uic_steps;
lv_obj_t * ui_steps = NULL;
lv_obj_t * ui_label5 = NULL;
lv_obj_t * ui_stepscount = NULL;
lv_obj_t * ui_stop = NULL;
lv_obj_t * ui_start = NULL;
lv_obj_t * ui_wis = NULL;
lv_obj_t * ui_safe = NULL;
lv_obj_t * ui_label8 = NULL;
lv_obj_t * ui_label9 = NULL;
lv_obj_t * ui_label10 = NULL;
lv_obj_t * ui_label1 = NULL;
// event funtions
void ui_event_steps(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_audio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_audio_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_time, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_time_screen_init);
    }
}

// build funtions

void ui_steps_screen_init(void)
{
    ui_steps = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_steps, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_steps, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_steps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label5 = lv_label_create(ui_steps);
    lv_obj_set_width(ui_label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label5, 0);
    lv_obj_set_y(ui_label5, -200);
    lv_obj_set_align(ui_label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label5, "STAPPEN");
    lv_obj_set_style_text_color(ui_label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stepscount = lv_label_create(ui_steps);
    lv_obj_set_width(ui_stepscount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stepscount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stepscount, 0);
    lv_obj_set_y(ui_stepscount, -120);
    lv_obj_set_align(ui_stepscount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stepscount, "12345");
    lv_obj_set_style_text_font(ui_stepscount, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stop = lv_button_create(ui_steps);
    lv_obj_set_width(ui_stop, 100);
    lv_obj_set_height(ui_stop, 50);
    lv_obj_set_x(ui_stop, 125);
    lv_obj_set_y(ui_stop, 0);
    lv_obj_set_align(ui_stop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_stop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_stop, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_stop, lv_color_hex(0xFC0207), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_stop, lv_color_hex(0x06B64B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_stop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_stop, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_stop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_stop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_stop, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_start = lv_button_create(ui_steps);
    lv_obj_set_width(ui_start, 100);
    lv_obj_set_height(ui_start, 50);
    lv_obj_set_x(ui_start, -125);
    lv_obj_set_y(ui_start, 0);
    lv_obj_set_align(ui_start, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_start, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_start, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_start, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_start, lv_color_hex(0x06B64B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_start, lv_color_hex(0xFC0207), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_start, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_start, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_start, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wis = lv_button_create(ui_steps);
    lv_obj_set_width(ui_wis, 100);
    lv_obj_set_height(ui_wis, 50);
    lv_obj_set_align(ui_wis, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wis, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_wis, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_wis, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wis, lv_color_hex(0x4304F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wis, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wis, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wis, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wis, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_wis, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wis, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wis, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_safe = lv_button_create(ui_steps);
    lv_obj_set_width(ui_safe, 100);
    lv_obj_set_height(ui_safe, 50);
    lv_obj_set_x(ui_safe, 0);
    lv_obj_set_y(ui_safe, 160);
    lv_obj_set_align(ui_safe, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_safe, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_safe, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_safe, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_safe, lv_color_hex(0xF905E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_safe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_safe, lv_color_hex(0xFBFC09), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_safe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_safe, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label8 = lv_label_create(ui_steps);
    lv_obj_set_width(ui_label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label8, -125);
    lv_obj_set_y(ui_label8, 0);
    lv_obj_set_align(ui_label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label8, "Start");
    lv_obj_set_style_text_color(ui_label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label8, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label9 = lv_label_create(ui_steps);
    lv_obj_set_width(ui_label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label9, "Wis");
    lv_obj_set_style_text_color(ui_label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label9, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label10 = lv_label_create(ui_steps);
    lv_obj_set_width(ui_label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label10, 125);
    lv_obj_set_y(ui_label10, 0);
    lv_obj_set_align(ui_label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label10, "Stop");
    lv_obj_set_style_text_color(ui_label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label10, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label1 = lv_label_create(ui_steps);
    lv_obj_set_width(ui_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label1, 0);
    lv_obj_set_y(ui_label1, 159);
    lv_obj_set_align(ui_label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1, "Save");
    lv_obj_set_style_text_font(ui_label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Event callbacks voor Start/Stop/Wis/Save knoppen
    lv_obj_add_event_cb(ui_start, ui_event_start_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_stop, ui_event_stop_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_wis, ui_event_wis_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_safe, ui_event_save_clicked, LV_EVENT_CLICKED, NULL);

    lv_obj_add_event_cb(ui_steps, ui_event_steps, LV_EVENT_ALL, NULL);
    uic_steps = ui_steps;
    uic_stepscount = ui_stepscount;
    uic_stop = ui_stop;
    uic_wis = ui_wis;

}

void ui_steps_screen_destroy(void)
{
    if(ui_steps) lv_obj_del(ui_steps);

    // NULL screen variables
    uic_steps = NULL;
    ui_steps = NULL;
    ui_label5 = NULL;
    uic_stepscount = NULL;
    ui_stepscount = NULL;
    uic_stop = NULL;
    ui_stop = NULL;
    ui_start = NULL;
    uic_wis = NULL;
    ui_wis = NULL;
    ui_safe = NULL;
    ui_label8 = NULL;
    ui_label9 = NULL;
    ui_label10 = NULL;
    ui_label1 = NULL;

}
