// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_STEPS_H
#define UI_STEPS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_steps
extern void ui_steps_screen_init(void);
extern void ui_steps_screen_destroy(void);
extern void ui_event_steps(lv_event_t * e);
extern lv_obj_t * ui_steps;
extern lv_obj_t * ui_label5;
extern lv_obj_t * ui_stepscount;
extern lv_obj_t * ui_stop;
extern lv_obj_t * ui_start;
extern lv_obj_t * ui_wis;
extern lv_obj_t * ui_safe;
extern lv_obj_t * ui_label8;
extern lv_obj_t * ui_label9;
extern lv_obj_t * ui_label10;
extern lv_obj_t * ui_label1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_steps;
extern lv_obj_t * uic_stepscount;
extern lv_obj_t * uic_stop;
extern lv_obj_t * uic_wis;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

