// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settings
extern void ui_settings_screen_init(void);
extern void ui_settings_screen_destroy(void);
extern void ui_event_settings(lv_event_t * e);
extern lv_obj_t * ui_settings;
extern lv_obj_t * ui_helderheid;
extern void ui_event_slider1(lv_event_t * e);
extern lv_obj_t * ui_slider1;
extern lv_obj_t * ui_percentage;
extern lv_obj_t * ui_ssid;
extern lv_obj_t * ui_password;
extern lv_obj_t * ui_swwifi;
extern lv_obj_t * ui_save;
extern lv_obj_t * ui_label11;
extern lv_obj_t * ui_label13;
extern lv_obj_t * ui_label14;
// CUSTOM VARIABLES
extern lv_obj_t * uic_settings;
extern lv_obj_t * uic_helderheid;
extern lv_obj_t * uic_Slider1;
extern lv_obj_t * uic_percentage;
extern lv_obj_t * uic_ssid;
extern lv_obj_t * uic_password;
extern lv_obj_t * uic_swwifi;
extern lv_obj_t * uic_save;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

