// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_TIME_H
#define UI_TIME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_time
extern void ui_time_screen_init(void);
extern void ui_time_screen_destroy(void);
extern void ui_event_time(lv_event_t * e);
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_tijd;
extern lv_obj_t * ui_sec;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_day;
extern lv_obj_t * ui_wifisignal;
extern lv_obj_t * ui_batterie;
// CUSTOM VARIABLES
extern lv_obj_t * uic_time;
extern lv_obj_t * uic_time_hm;
extern lv_obj_t * uic_sec;
extern lv_obj_t * uic_date;
extern lv_obj_t * uic_day;
extern lv_obj_t * uic_wifisignal;
extern lv_obj_t * uic_batterie;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

