// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_batterie;
lv_obj_t * uic_wifisignal;
lv_obj_t * uic_day;
lv_obj_t * uic_date;
lv_obj_t * uic_sec;
lv_obj_t * uic_time_hm;
lv_obj_t * uic_time;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_tijd = NULL;
lv_obj_t * ui_sec = NULL;
lv_obj_t * ui_date = NULL;
lv_obj_t * ui_day = NULL;
lv_obj_t * ui_wifisignal = NULL;
lv_obj_t * ui_batterie = NULL;
// event funtions
void ui_event_time(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_steps, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_steps_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_settings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_settings_screen_init);
    }
}

// build funtions

void ui_time_screen_init(void)
{
    ui_time = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_time, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tijd = lv_label_create(ui_time);
    lv_obj_set_width(ui_tijd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tijd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tijd, -1);
    lv_obj_set_y(ui_tijd, -90);
    lv_obj_set_align(ui_tijd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tijd, "23:59");
    lv_obj_set_style_text_color(ui_tijd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tijd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tijd, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sec = lv_label_create(ui_time);
    lv_obj_set_width(ui_sec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sec, 43);
    lv_obj_set_y(ui_sec, -50);
    lv_obj_set_align(ui_sec, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sec, "59");
    lv_obj_set_style_text_color(ui_sec, lv_color_hex(0x07AB66), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sec, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sec, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_time);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, 0);
    lv_obj_set_y(ui_date, 100);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "30 september 2026");
    lv_obj_set_style_text_font(ui_date, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day = lv_label_create(ui_time);
    lv_obj_set_width(ui_day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day, 0);
    lv_obj_set_y(ui_day, 140);
    lv_obj_set_align(ui_day, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day, "zaterdag");
    lv_obj_set_style_text_font(ui_day, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifisignal = lv_image_create(ui_time);
    lv_image_set_src(ui_wifisignal, &ui_img_wifi_strong_green_3arc_25x25_png);
    lv_obj_set_width(ui_wifisignal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifisignal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifisignal, 30);
    lv_obj_set_y(ui_wifisignal, -235);
    lv_obj_set_align(ui_wifisignal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifisignal, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wifisignal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batterie = lv_image_create(ui_time);
    lv_image_set_src(ui_batterie, &ui_img_battery_strong_green_3bars_25x25_png);
    lv_obj_set_width(ui_batterie, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batterie, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batterie, -30);
    lv_obj_set_y(ui_batterie, -235);
    lv_obj_set_align(ui_batterie, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_batterie, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_batterie, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_time, ui_event_time, LV_EVENT_ALL, NULL);
    uic_time = ui_time;
    uic_time_hm = ui_tijd;
    uic_sec = ui_sec;
    uic_date = ui_date;
    uic_day = ui_day;
    uic_wifisignal = ui_wifisignal;
    uic_batterie = ui_batterie;

}

void ui_time_screen_destroy(void)
{
    if(ui_time) lv_obj_del(ui_time);

    // NULL screen variables
    uic_time = NULL;
    ui_time = NULL;
    uic_time_hm = NULL;
    ui_tijd = NULL;
    uic_sec = NULL;
    ui_sec = NULL;
    uic_date = NULL;
    ui_date = NULL;
    uic_day = NULL;
    ui_day = NULL;
    uic_wifisignal = NULL;
    ui_wifisignal = NULL;
    uic_batterie = NULL;
    ui_batterie = NULL;

}
