// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_viewerfiles;
lv_obj_t * ui_viewerfiles = NULL;
// event funtions

// build funtions

void ui_viewerfiles_screen_init(void)
{
    ui_viewerfiles = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_viewerfiles, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_viewerfiles, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_viewerfiles, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_viewerfiles, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Event handler voor scherm geladen
    lv_obj_add_event_cb(ui_viewerfiles, ui_event_viewerfiles_loaded, LV_EVENT_SCREEN_LOADED, NULL);

    uic_viewerfiles = ui_viewerfiles;

}

void ui_viewerfiles_screen_destroy(void)
{
    if(ui_viewerfiles) lv_obj_del(ui_viewerfiles);

    // NULL screen variables
    uic_viewerfiles = NULL;
    ui_viewerfiles = NULL;

}
