// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_VIEWERFILES_H
#define UI_VIEWERFILES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_viewerfiles
extern void ui_viewerfiles_screen_init(void);
extern void ui_viewerfiles_screen_destroy(void);
extern lv_obj_t * ui_viewerfiles;
// CUSTOM VARIABLES
extern lv_obj_t * uic_viewerfiles;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

