// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_VIEWERIMAGES_H
#define UI_VIEWERIMAGES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_viewerimages
extern void ui_viewerimages_screen_init(void);
extern void ui_viewerimages_screen_destroy(void);
extern lv_obj_t * ui_viewerimages;
// CUSTOM VARIABLES
extern lv_obj_t * uic_viewerimages;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

