// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_viewerimages;
lv_obj_t * ui_viewerimages = NULL;
// event funtions

// build funtions

void ui_viewerimages_screen_init(void)
{
    ui_viewerimages = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_viewerimages, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_viewerimages, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_viewerimages, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Event handler voor scherm geladen
    lv_obj_add_event_cb(ui_viewerimages, ui_event_viewerimages_loaded, LV_EVENT_SCREEN_LOADED, NULL);

    uic_viewerimages = ui_viewerimages;

}

void ui_viewerimages_screen_destroy(void)
{
    if(ui_viewerimages) lv_obj_del(ui_viewerimages);

    // NULL screen variables
    uic_viewerimages = NULL;
    ui_viewerimages = NULL;

}
